version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: pg
    versions:
    - "> 0.21.0"
  - dependency-name: reek
    versions:
    - ">= 5.3.a, < 5.4"
  - dependency-name: reek
    versions:
    - ">= 5.4.a, < 5.5"
  - dependency-name: reek
    versions:
    - ">= 5.5.a, < 5.6"
  - dependency-name: rubocop
    versions:
    - ">= 0.81.a, < 0.82"
  - dependency-name: rubocop
    versions:
    - ">= 0.82.a, < 0.83"
  - dependency-name: rubocop
    versions:
    - ">= 0.85.a, < 0.86"
  - dependency-name: rubocop
    versions:
    - ">= 0.86.a, < 0.87"
  - dependency-name: rubocop
    versions:
    - ">= 0.87.a, < 0.88"
  - dependency-name: rubocop
    versions:
    - "> 1.5.2"
  - dependency-name: rubocop
    versions:
    - ">= 1.7.a, < 1.8"
  - dependency-name: rubocop
    versions:
    - ">= 1.8.a, < 1.9"
  - dependency-name: rubocop
    versions:
    - ">= 1.9.a, < 1.10"
  - dependency-name: fugit
    versions:
    - 1.4.3
  - dependency-name: timecop
    versions:
    - 0.9.3
