---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - ruby
  fixme:
    enabled: true
  rubocop:
    enabled: true
    channel: rubocop-0-54
ratings:
  paths:
  - "**.rb"
  - "**.md"
