version: "2"

# https://docs.codeclimate.com/docs/advanced-configuration
checks:
  # This is (broadly) covered by Rubocop's Cyclomatic Complexity
  method-complexity:
    enabled: false

plugins:
  rubocop:
    enabled: true
    channel: rubocop-1-26
