version: "2"

# https://docs.codeclimate.com/docs/advanced-configuration
checks:
  method-complexity:
    enabled: true
    config:
      threshold: 8

plugins:
  rubocop:
    enabled: true
    channel: rubocop-1-26
