AllCops:
  TargetRubyVersion: 2.4
  DisplayCopNames: true
Layout/DotPosition:
  EnforcedStyle: leading
Lint/BlockAlignment:
  EnforcedStyleAlignWith: start_of_block
Metrics/BlockLength:
  Exclude:
  - 'Rakefile'
  - '**/*.rake'
  - '**/*.gemspec'
  - '**/spec/**/*.rb'
Metrics/LineLength:
  Max: 100
Metrics/MethodLength:
  Max: 30
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
