HalfHourlyTestJob:
  cron: "0,30 * * * *"

WithArgsTestJob:
  cron: "40 11 * * *"
  args:
    - My Args
    - 1234
    - some_hash: true

daily_test_job_specifying_class:
  class: SpecifiedByClassTestJob
  cron: "10 3 * * *"
  schedule_type: default

DailyTestJob:
  cron: "10 6 * * *"
  schedule_type: every_event

TwiceDailyTestJob:
  cron: "10 11,16 * * *"
  priority: 35
  queue: backlog
  schedule_type: every_event

TimezoneTestJob:
  cron: "5 7 1 * * America/Los_Angeles"
  schedule_type: every_event
